name: Build, Push Docker Image to ECR, and Update Lambda

on:
  push:
    branches:
      - main

jobs:
  build-push-update:
    name: Build, Delete Old Image, Push to AWS ECR, and Update Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Get Image Digest of Previous Image
        id: get_digest
        run: |
          PREVIOUS_DIGEST=$(aws ecr list-images --repository-name ${{ secrets.ECR_REPOSITORY }} --query 'imageIds[0].imageDigest' --output text 2>/dev/null || echo "")
          if [[ "$PREVIOUS_DIGEST" == "None" || -z "$PREVIOUS_DIGEST" ]]; then
            echo "No previous image found. Skipping deletion."
          else
            echo "PREVIOUS_DIGEST=$PREVIOUS_DIGEST" >> $GITHUB_ENV
          fi

      - name: Delete Previous Docker Image (if exists)
        if: env.PREVIOUS_DIGEST != ''
        run: |
          echo "Deleting previous image: $PREVIOUS_DIGEST"
          aws ecr batch-delete-image --repository-name ${{ secrets.ECR_REPOSITORY }} --image-ids imageDigest=$PREVIOUS_DIGEST

      - name: Build Docker Image (Using `api/` Folder)
        run: |
          docker build --provenance=false -t schedsyncapi ./api

      - name: Tag Docker Image
        run: |
          docker tag schedsyncapi:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Update AWS Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --image-uri ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
