name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Production Dependencies
        run: |
          cd api
          npm install --only=prod --force  # Install only dependencies, skipping devDependencies

      - name: Create Lambda Layer 1 (Core Dependencies)
        run: |
          cd api
          mkdir -p layer1/nodejs
          
          cp -r node_modules/express layer1/nodejs/
          cp -r node_modules/cors layer1/nodejs/
          cp -r node_modules/aws-serverless-express layer1/nodejs/
          cp -r node_modules/dotenv layer1/nodejs/
          cp -r node_modules/jsonwebtoken layer1/nodejs/
          cp -r node_modules/zod layer1/nodejs/
          cp -r node_modules/pg layer1/nodejs/
          cp -r node_modules/passport layer1/nodejs/
          cp -r node_modules/passport-google-oauth20 layer1/nodejs/
          cp -r node_modules/lodash layer1/nodejs/
          cp -r node_modules/axios layer1/nodejs/
          cp -r node_modules/node-cron layer1/nodejs/

          cd layer1
          zip -r layer1.zip nodejs
          aws lambda publish-layer-version \
            --layer-name "schedsync-layer-1" \
            --content "fileb://layer1.zip" \
            --compatible-runtimes "nodejs22.x" \
            --region "${{ secrets.AWS_REGION }}"

      - name: Create Lambda Layer 2 (AI & DB Dependencies)
        run: |
          cd api
          mkdir -p layer2/nodejs
          
          cp -r node_modules/@prisma layer2/nodejs/
          cp -r node_modules/@google layer2/nodejs/
          cp -r node_modules/@langchain layer2/nodejs/
          cp -r node_modules/@pinecone-database layer2/nodejs/
          cp -r node_modules/openai layer2/nodejs/
          cp -r node_modules/serverless-http layer2/nodejs/

          cd layer2
          zip -r layer2.zip nodejs
          aws lambda publish-layer-version \
            --layer-name "schedsync-layer-2" \
            --content "fileb://layer2.zip" \
            --compatible-runtimes "nodejs22.x" \
            --region "${{ secrets.AWS_REGION }}"


      - name: Compile TypeScript
        run: |
          cd api
          npm run build

      - name: Package and Deploy Application Code to AWS Lambda
        run: |
          cd api
          
          # Package only app code (excluding node_modules)
          zip -r deploy.zip ./dist/* package.json package-lock.json
          
          # Upload the function code
          aws lambda update-function-code \
            --function-name schedsyncapi \
            --zip-file fileb://deploy.zip \
            --region ${{ secrets.AWS_REGION }}

      - name: Attach Layers to Lambda Function
        run: |
          aws lambda update-function-configuration \
            --function-name schedsyncapi \
            --layers \
              arn:aws:lambda:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:layer:schedsync-layer-1:latest \
              arn:aws:lambda:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:layer:schedsync-layer-2:latest \
            --region ${{ secrets.AWS_REGION }}
