name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Change to 'master' if needed

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Match your AWS Lambda runtime

      - name: Install Dependencies
        run: |
          cd api
          npm ci  # Install dependencies (clean install)

      - name: Compile TypeScript
        run: |
          cd api
          npm run build  # This should run `tsc`

      - name: Package and Upload to AWS Lambda
        run: |
          cd api
          zip -r deploy.zip ./dist/* package.json package-lock.json
          aws lambda update-function-code --function-name your-lambda-function-name --zip-file fileb://deploy.zip
